document.writeln("<div class=\'nav\'>");
document.writeln("    <div class=\'content nav-box\'>");
document.writeln("        <div class=\'logo\'>");
document.writeln("            <img src=\'images/logo.png\' alt=\'\'>");
document.writeln("        </div>");
document.writeln("        <ul>");
document.writeln("            <li class=\'choose\'>首页</li>");
document.writeln("            <li>高端定制</li>");
document.writeln("            <li>移动应用</li>");
document.writeln("            <li>行业方案</li>");
document.writeln("            <li>关于我们</li>");
document.writeln("        </ul>");
document.writeln("        <div class=\'phone\'>123456789</div>");
document.writeln("    </div>");
document.writeln("</div>");